### ISSUE TITLE
Icon not used in React project?

### ISSUE THREAD

**Issue by mirkonasato** [ionic-team/app-wizard-issues#1]
**Describe the bug**

The start wizard asks to _Pick an icon_, but that icon doesn't seem to be used anywhere in the generated project.

**To Reproduce**

Go to the [start wizard](https://ionicframework.com/start), pick an icon, select _React_ as the framework, create app, fetch the project with `ionic start --start-id ...`

Open the project. There's a `resources` folder with `icon.png` and `splash.png`. But `public/manifest.json` references `favicon.png` and `icon.png` in `public/assets/icon` and they both show the Ionic logo. 

After running `ionic capacitor add android`, the Android project uses the Capacitor logo for all launcher icons and splash screen.

**Expected behavior**
The selected icon should be used everywhere, as favicon, mobile app icons and splash screens.

This is using the `@ionic/cli` v6.5.0.

**Comment by mlynch** [comment]
Thanks. You need to run the `cordova-res` command to generate the icons from the resources folder after you've added your platforms. I know it's confusing, we are working to make this more seamless.

**Comment by mirkonasato** [comment]
Oh, I thought `cordova-res` was just for Cordova given the name, but it does work with [Capacitor as well](https://github.com/ionic-team/cordova-res#capacitor). Good to know!

**Comment by mlynch** [comment]
Yea we will be changing that soon! Thanks, going to close
