### ISSUE TITLE
Confusing error when trying to log in with wrong password

### ISSUE THREAD

**Issue by dandv** [ionic-team/app-wizard-issues#2]
**Describe the bug**
I wanted to try out the app wizard. Entered my name, email, desired username and password, then got an error message that my username existed. Trying to log in with it resulted in this:

![image](https://user-images.githubusercontent.com/33569/79078096-1ae58700-7d5a-11ea-94a5-69cc0c4b2972.png)

**To Reproduce**
1. Go to https://ionicframework.com/start
2. Choose a name etc. and click Continue
3. No the next page, choose "Already have an account? Log in"
4. Enter an email and a wrong password.

**Expected behavior**
An "invalid login" screen, with options to sign up or recover password.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome 80

**Update**
Got the same error when I signed up for a new username (`dandvd`).

Does the wizard work?

**Comment by mlynch** [comment]
Sorry about that, the server had some memory issues that we've since resolved. Things are looking better on my end now and made some configuration changes to avoid this in the future. Also making a fix to the login page to better report auth errors
